apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      name: short-api
      labels:
        components: backend
    spec:
      containers:
        - name: short-api
          image: antonlarichev/short-api:v1.0
          #imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: short-api-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: test
              mountPath: /etc/test # проверим маунт в поде
              readOnly: true
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          startupProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            periodSeconds: 5
            failureThreshold: 5  
      volumes:
        - name: test
          configMap: 
            name: demo-config          